import type { Metadata } from 'next'
import './globals.css'
import { Ai } from '../context/ai'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <Ai>
      <html lang="en">
        <body className="bg-background h-screen">{children}</body>
      </html>
    </Ai>
  )
}
