/** @type {import('tailwindcss').Config} */
const plugin = require('tailwindcss/plugin')

module.exports = {
  theme: {
    extend: {
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        inactive: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: {
          DEFAULT: 'hsl(var(--border))',
          accent: 'hsl(var(--border-accent))',
          hover: 'hsl(var(--border-hover))',
          active: 'hsl(var(--border-active))',
          validation: 'hsl(var(--border-validation))',
          'active-tint': 'hsl(var(--border-active-tint))',
        },
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          1: 'hsl(var(--chart-1))',
          2: 'hsl(var(--chart-2))',
          3: 'hsl(var(--chart-3))',
          4: 'hsl(var(--chart-4))',
          5: 'hsl(var(--chart-5))',
        },
        action: {
          DEFAULT: 'hsl(var(--action))',
          foreground: 'hsl(var(--action-foreground))',
          primary: 'var(--action-primary)',
          secondary: 'var(--action-secondary)',
        },
        success: {
          DEFAULT: 'hsl(var(--success))',
          foreground: 'hsl(var(--success-foreground))',
        },
        error: {
          DEFAULT: 'hsl(var(--error))',
          foreground: 'hsl(var(--error-foreground))',
        },
        surface: {
          DEFAULT: 'hsl(var(--surface-3))',
          0: 'hsl(var(--surface-0))',
          1: 'hsl(var(--surface-1))',
          2: 'hsl(var(--surface-2))',
          3: 'hsl(var(--surface-3))',
        },
      },
    },
  },
  plugins: [
    plugin(function ({ addBase }) {
      addBase({
        ':root': {
          '--background': '0 0% 100%',
          '--foreground': '0 0% 3.9%',
          '--card': '0 0% 100%',
          '--card-foreground': '0 0% 3.9%',
          '--popover': '0 0% 100%',
          '--popover-foreground': '0 0% 3.9%',
          '--primary': '208 100% 50%',
          '--primary-foreground': '0 0% 98%',
          '--secondary': '210 16% 93%',
          '--secondary-foreground': '210 11% 15% / 0.75',
          '--muted': '0 0% 96.1%',
          '--muted-foreground': '0 0% 45.1%',
          '--accent': '0 0% 96.1%',
          '--accent-foreground': '0 0% 9%',
          '--destructive': '0 84.2% 60.2%',
          '--destructive-foreground': '0 0% 98%',
          '--border': '0 0% 89.8%',
          '--input': '0 0% 89.8%',
          '--ring': '0 0% 3.9%',
          '--chart-1': '12 76% 61%',
          '--chart-2': '173 58% 39%',
          '--chart-3': '197 37% 24%',
          '--chart-4': '43 74% 66%',
          '--chart-5': '27 87% 67%',
          '--radius': '0.5rem',
          '--action': '208 100% 50%',
          '--action-foreground': '0 0% 98%',
          '--action-shadow': '205 100% 94%',
          '--success': '160 84% 39%',
          '--success-foreground': '0 0% 98%',
          '--error': '0 84.2% 60.2%',
          '--error-foreground': '0 0% 98%',
          '--surface-0': '0 0% 100%',
          '--surface-1': '220 33% 98%',
          '--surface-2': '220 21% 95%',
          '--surface-3': '216 23% 91%',
          '--border-accent': '240 5% 65%',
          '--border-hover': '216 23% 91%',
          '--border-active': '209 100% 50%',
          '--border-validation': '346 100% 50%',
          '--border-active-tint': '206 100% 91%',
        },
        '@media (prefers-color-scheme: dark)': {
          ':root': {
            '--background': '0 0% 3.9%',
            '--foreground': '0 0% 98%',
            '--card': '0 0% 3.9%',
            '--card-foreground': '0 0% 98%',
            '--popover': '0 0% 3.9%',
            '--popover-foreground': '0 0% 98%',
            '--primary': '208 100% 50%',
            '--primary-foreground': '0 0% 98%',
            '--secondary': '210 10% 23%',
            '--secondary-foreground': '210 13.8% 88.6% / 0.75',
            '--muted': '0 0% 14.9%',
            '--muted-foreground': '0 0% 63.9%',
            '--accent': '0 0% 14.9%',
            '--accent-foreground': '0 0% 98%',
            '--destructive': '0 62.8% 30.6%',
            '--destructive-foreground': '0 0% 98%',
            '--border': '0 0% 14.9%',
            '--input': '0 0% 14.9%',
            '--ring': '0 0% 83.1%',
            '--chart-1': '220 70% 50%',
            '--chart-2': '160 60% 45%',
            '--chart-3': '30 80% 55%',
            '--chart-4': '280 65% 60%',
            '--chart-5': '340 75% 55%',
            '--action': '208 100% 50%',
            '--action-foreground': '0 0% 98%',
            '--action-shadow': '205 46% 39%',
            '--surface-0': '240 6% 14%',
            '--surface-1': '230 6% 19%',
            '--surface-2': '227 8% 23%',
            '--surface-3': '227 6% 28%',
          },
        },
        '*': {
          '@apply border-border': {},
        },
        body: {
          '@apply bg-background text-foreground': {},
        },
      })
    }),
  ],
}
